
#Get the HclHyperflexSoftwareCompatibilityInfo to delete
$HclHyperflexSoftwareCompatibilityInfo = Get-IntersightHclHyperflexSoftwareCompatibilityInfo -Name HclHyperflexSoftwareCompatibilityInfoName
$HclHyperflexSoftwareCompatibilityInfo | Remove-IntersightHclHyperflexSoftwareCompatibilityInfo

#Remove the HclHyperflexSoftwareCompatibilityInfo by Moid.
Remove-IntersightHclHyperflexSoftwareCompatibilityInfo -Moid 123bc2222287wee
