
#Get the CapabilityServerSchemaDescriptor to delete
$CapabilityServerSchemaDescriptor = Remove-IntersightCapabilityServerSchemaDescriptor -Name CapabilityServerSchemaDescriptorName
$CapabilityServerSchemaDescriptor | Remove-IntersightCapabilityServerSchemaDescriptor

#Remove the server profile by Moid.
Remove-IntersightCapabilityServerSchemaDescriptor -Moid 123bc2222287wee
