
#Get the CapabilitySiocModuleManufacturingDef to delete
$CapabilitySiocModuleManufacturingDef = Remove-IntersightCapabilitySiocModuleManufacturingDef -Name CapabilitySiocModuleManufacturingDefName
$CapabilitySiocModuleManufacturingDef | Remove-IntersightCapabilitySiocModuleManufacturingDef

#Remove the server profile by Moid.
Remove-IntersightCapabilitySiocModuleManufacturingDef -Moid 123bc2222287wee
