
#Get the CapabilitySiocModuleManufacturingDef to Update
$CapabilitySiocModuleManufacturingDef = Get-IntersightCapabilitySiocModuleManufacturingDef -Name CapabilitySiocModuleManufacturingDefName
$CapabilitySiocModuleManufacturingDef | Set-IntersightCapabilitySiocModuleManufacturingDef -Description 'Updated description'