
#Get the CapabilitySwitchManufacturingDef to Update
$CapabilitySwitchManufacturingDef = Get-IntersightCapabilitySwitchManufacturingDef -Name CapabilitySwitchManufacturingDefName
$CapabilitySwitchManufacturingDef | Set-IntersightCapabilitySwitchManufacturingDef -Description 'Updated description'
