
#Get the CapabilityPortGroupAggregationDef to Update
$CapabilityPortGroupAggregationDef = Get-IntersightCapabilityPortGroupAggregationDef -Name CapabilityPortGroupAggregationDefName
$CapabilityPortGroupAggregationDef | Set-IntersightCapabilityPortGroupAggregationDef -Description 'Updated description'