
#Get the SoftwarerepositoryCategorySupportConstraint to delete
$SoftwarerepositoryCategorySupportConstraint = Remove-IntersightSoftwarerepositoryCategorySupportConstraint -Name SoftwarerepositoryCategorySupportConstraintName
$SoftwarerepositoryCategorySupportConstraint | Remove-IntersightSoftwarerepositoryCategorySupportConstraint

#Remove the server profile by Moid.
Remove-IntersightSoftwarerepositoryCategorySupportConstraint -Moid 123bc2222287wee
