
#Get the HyperflexHxapVirtualMachineNetworkInterface to delete
$HyperflexHxapVirtualMachineNetworkInterface = Remove-IntersightHyperflexHxapVirtualMachineNetworkInterface -Name HyperflexHxapVirtualMachineNetworkInterfaceName
$HyperflexHxapVirtualMachineNetworkInterface | Remove-IntersightHyperflexHxapVirtualMachineNetworkInterface

#Remove the server profile by Moid.
Remove-IntersightHyperflexHxapVirtualMachineNetworkInterface -Moid 123bc2222287wee
