
#Get the HyperflexClusterBackupPolicyDeployment to Update
$HyperflexClusterBackupPolicyDeployment = Get-IntersightHyperflexClusterBackupPolicyDeployment -Name HyperflexClusterBackupPolicyDeploymentName
$HyperflexClusterBackupPolicyDeployment | Set-IntersightHyperflexClusterBackupPolicyDeployment -Description 'Updated description'
