
#Get the HyperflexExtIscsiStoragePolicy to Update
$HyperflexExtIscsiStoragePolicy = Get-IntersightHyperflexExtIscsiStoragePolicy -Name HyperflexExtIscsiStoragePolicyName
$HyperflexExtIscsiStoragePolicy | Set-IntersightHyperflexExtIscsiStoragePolicy -Description 'Updated description'
