
#Get the HyperflexLocalCredentialPolicy to Update
$HyperflexLocalCredentialPolicy = Get-IntersightHyperflexLocalCredentialPolicy -Name HyperflexLocalCredentialPolicyName
$HyperflexLocalCredentialPolicy | Set-IntersightHyperflexLocalCredentialPolicy -Description 'Updated description'
