
#Get the HyperflexServerFirmwareVersion to Update
$HyperflexServerFirmwareVersion = Get-IntersightHyperflexServerFirmwareVersion -Name HyperflexServerFirmwareVersionName
$HyperflexServerFirmwareVersion | Set-IntersightHyperflexServerFirmwareVersion -Description 'Updated description'
