
#Get the HyperflexSoftwareDistributionComponent to Update
$HyperflexSoftwareDistributionComponent = Get-IntersightHyperflexSoftwareDistributionComponent -Name HyperflexSoftwareDistributionComponentName
$HyperflexSoftwareDistributionComponent | Set-IntersightHyperflexSoftwareDistributionComponent -Description 'Updated description'
