#
# Cisco Intersight
# Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-07-16T08:45:19Z.
# Version: 1.0.9-2020
# Contact: intersight@cisco.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Consolidated view of Blades and RackUnits.

.PARAMETER Moid
The unique identifier of this Managed Object instance.
.PARAMETER Owners
No description available.
.PARAMETER Tags
No description available.
.PARAMETER VersionContext
No description available.
.PARAMETER Parent
No description available.
.PARAMETER KvmIpAddresses
No description available.
.PARAMETER EquipmentChassis
No description available.
.PARAMETER InventoryDeviceInfo
No description available.
.PARAMETER RegisteredDevice
No description available.
.OUTPUTS

ComputePhysicalSummary<PSCustomObject>
#>

function Initialize-IntersightComputePhysicalSummary {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Moid},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Owners},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Tags},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${VersionContext},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Parent},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${KvmIpAddresses},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${EquipmentChassis},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${InventoryDeviceInfo},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${RegisteredDevice}
    )

    Process {
        'Creating PSCustomObject: Intersight => IntersightComputePhysicalSummary' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        
        $PSO = [PSCustomObject]@{
            "Moid" = ${Moid}
            "Owners" = ${Owners}
            "Tags" = ${Tags}
            "VersionContext" = ${VersionContext}
            "Parent" = ${Parent}
            "KvmIpAddresses" = ${KvmIpAddresses}
            "EquipmentChassis" = ${EquipmentChassis}
            "InventoryDeviceInfo" = ${InventoryDeviceInfo}
            "RegisteredDevice" = ${RegisteredDevice}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ComputePhysicalSummary<PSCustomObject>

.DESCRIPTION

Convert from JSON to ComputePhysicalSummary<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ComputePhysicalSummary<PSCustomObject>
#>
function ConvertFrom-IntersightJsonToComputePhysicalSummary {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: Intersight => IntersightComputePhysicalSummary' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in IntersightComputePhysicalSummary
        $AllProperties = ("AccountMoid", "ClassId", "CreateTime", "DomainGroupMoid", "ModTime", "Moid", "ObjectType", "Owners", "SharedScope", "Tags", "VersionContext", "Ancestors", "Parent", "PermissionResources", "DisplayNames", "AdminPowerState", "AssetTag", "AvailableMemory", "BiosPostComplete", "ChassisId", "ConnectionStatus", "CpuCapacity", "DeviceMoId", "Dn", "FaultSummary", "Firmware", "Ipv4Address", "KvmIpAddresses", "ManagementMode", "MemorySpeed", "MgmtIpAddress", "Model", "Name", "NumAdaptors", "NumCpuCores", "NumCpuCoresEnabled", "NumCpus", "NumEthHostInterfaces", "NumFcHostInterfaces", "NumThreads", "OperPowerState", "OperState", "Operability", "PlatformType", "Presence", "Revision", "Rn", "ScaledMode", "Serial", "ServerId", "ServiceProfile", "SlotId", "SourceObjectType", "TopologyScanStatus", "TotalMemory", "UserLabel", "Uuid", "Vendor", "EquipmentChassis", "InventoryDeviceInfo", "RegisteredDevice")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property `ClassId` missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ClassId"))) {
            throw "Error! JSON cannot be serialized due to the required property `ClassId` missing."
        } else {
            $ClassId = $JsonParameters.PSobject.Properties["ClassId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ObjectType"))) {
            throw "Error! JSON cannot be serialized due to the required property `ObjectType` missing."
        } else {
            $ObjectType = $JsonParameters.PSobject.Properties["ObjectType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "AccountMoid"))) { #optional property not found
            $AccountMoid = $null
        } else {
            $AccountMoid = $JsonParameters.PSobject.Properties["AccountMoid"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "CreateTime"))) { #optional property not found
            $CreateTime = $null
        } else {
            $CreateTime = $JsonParameters.PSobject.Properties["CreateTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "DomainGroupMoid"))) { #optional property not found
            $DomainGroupMoid = $null
        } else {
            $DomainGroupMoid = $JsonParameters.PSobject.Properties["DomainGroupMoid"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ModTime"))) { #optional property not found
            $ModTime = $null
        } else {
            $ModTime = $JsonParameters.PSobject.Properties["ModTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Moid"))) { #optional property not found
            $Moid = $null
        } else {
            $Moid = $JsonParameters.PSobject.Properties["Moid"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Owners"))) { #optional property not found
            $Owners = $null
        } else {
            $Owners = $JsonParameters.PSobject.Properties["Owners"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "SharedScope"))) { #optional property not found
            $SharedScope = $null
        } else {
            $SharedScope = $JsonParameters.PSobject.Properties["SharedScope"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Tags"))) { #optional property not found
            $Tags = $null
        } else {
            $Tags = $JsonParameters.PSobject.Properties["Tags"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "VersionContext"))) { #optional property not found
            $VersionContext = $null
        } else {
            $VersionContext = $JsonParameters.PSobject.Properties["VersionContext"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Ancestors"))) { #optional property not found
            $Ancestors = $null
        } else {
            $Ancestors = $JsonParameters.PSobject.Properties["Ancestors"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Parent"))) { #optional property not found
            $Parent = $null
        } else {
            $Parent = $JsonParameters.PSobject.Properties["Parent"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "PermissionResources"))) { #optional property not found
            $PermissionResources = $null
        } else {
            $PermissionResources = $JsonParameters.PSobject.Properties["PermissionResources"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "DisplayNames"))) { #optional property not found
            $DisplayNames = $null
        } else {
            $DisplayNames = $JsonParameters.PSobject.Properties["DisplayNames"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "AdminPowerState"))) { #optional property not found
            $AdminPowerState = $null
        } else {
            $AdminPowerState = $JsonParameters.PSobject.Properties["AdminPowerState"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "AssetTag"))) { #optional property not found
            $AssetTag = $null
        } else {
            $AssetTag = $JsonParameters.PSobject.Properties["AssetTag"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "AvailableMemory"))) { #optional property not found
            $AvailableMemory = $null
        } else {
            $AvailableMemory = $JsonParameters.PSobject.Properties["AvailableMemory"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "BiosPostComplete"))) { #optional property not found
            $BiosPostComplete = $null
        } else {
            $BiosPostComplete = $JsonParameters.PSobject.Properties["BiosPostComplete"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ChassisId"))) { #optional property not found
            $ChassisId = $null
        } else {
            $ChassisId = $JsonParameters.PSobject.Properties["ChassisId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ConnectionStatus"))) { #optional property not found
            $ConnectionStatus = $null
        } else {
            $ConnectionStatus = $JsonParameters.PSobject.Properties["ConnectionStatus"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "CpuCapacity"))) { #optional property not found
            $CpuCapacity = $null
        } else {
            $CpuCapacity = $JsonParameters.PSobject.Properties["CpuCapacity"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "DeviceMoId"))) { #optional property not found
            $DeviceMoId = $null
        } else {
            $DeviceMoId = $JsonParameters.PSobject.Properties["DeviceMoId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Dn"))) { #optional property not found
            $Dn = $null
        } else {
            $Dn = $JsonParameters.PSobject.Properties["Dn"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "FaultSummary"))) { #optional property not found
            $FaultSummary = $null
        } else {
            $FaultSummary = $JsonParameters.PSobject.Properties["FaultSummary"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Firmware"))) { #optional property not found
            $Firmware = $null
        } else {
            $Firmware = $JsonParameters.PSobject.Properties["Firmware"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Ipv4Address"))) { #optional property not found
            $Ipv4Address = $null
        } else {
            $Ipv4Address = $JsonParameters.PSobject.Properties["Ipv4Address"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "KvmIpAddresses"))) { #optional property not found
            $KvmIpAddresses = $null
        } else {
            $KvmIpAddresses = $JsonParameters.PSobject.Properties["KvmIpAddresses"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ManagementMode"))) { #optional property not found
            $ManagementMode = $null
        } else {
            $ManagementMode = $JsonParameters.PSobject.Properties["ManagementMode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "MemorySpeed"))) { #optional property not found
            $MemorySpeed = $null
        } else {
            $MemorySpeed = $JsonParameters.PSobject.Properties["MemorySpeed"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "MgmtIpAddress"))) { #optional property not found
            $MgmtIpAddress = $null
        } else {
            $MgmtIpAddress = $JsonParameters.PSobject.Properties["MgmtIpAddress"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Model"))) { #optional property not found
            $Model = $null
        } else {
            $Model = $JsonParameters.PSobject.Properties["Model"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["Name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "NumAdaptors"))) { #optional property not found
            $NumAdaptors = $null
        } else {
            $NumAdaptors = $JsonParameters.PSobject.Properties["NumAdaptors"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "NumCpuCores"))) { #optional property not found
            $NumCpuCores = $null
        } else {
            $NumCpuCores = $JsonParameters.PSobject.Properties["NumCpuCores"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "NumCpuCoresEnabled"))) { #optional property not found
            $NumCpuCoresEnabled = $null
        } else {
            $NumCpuCoresEnabled = $JsonParameters.PSobject.Properties["NumCpuCoresEnabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "NumCpus"))) { #optional property not found
            $NumCpus = $null
        } else {
            $NumCpus = $JsonParameters.PSobject.Properties["NumCpus"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "NumEthHostInterfaces"))) { #optional property not found
            $NumEthHostInterfaces = $null
        } else {
            $NumEthHostInterfaces = $JsonParameters.PSobject.Properties["NumEthHostInterfaces"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "NumFcHostInterfaces"))) { #optional property not found
            $NumFcHostInterfaces = $null
        } else {
            $NumFcHostInterfaces = $JsonParameters.PSobject.Properties["NumFcHostInterfaces"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "NumThreads"))) { #optional property not found
            $NumThreads = $null
        } else {
            $NumThreads = $JsonParameters.PSobject.Properties["NumThreads"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "OperPowerState"))) { #optional property not found
            $OperPowerState = $null
        } else {
            $OperPowerState = $JsonParameters.PSobject.Properties["OperPowerState"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "OperState"))) { #optional property not found
            $OperState = $null
        } else {
            $OperState = $JsonParameters.PSobject.Properties["OperState"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Operability"))) { #optional property not found
            $Operability = $null
        } else {
            $Operability = $JsonParameters.PSobject.Properties["Operability"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "PlatformType"))) { #optional property not found
            $PlatformType = $null
        } else {
            $PlatformType = $JsonParameters.PSobject.Properties["PlatformType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Presence"))) { #optional property not found
            $Presence = $null
        } else {
            $Presence = $JsonParameters.PSobject.Properties["Presence"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Revision"))) { #optional property not found
            $Revision = $null
        } else {
            $Revision = $JsonParameters.PSobject.Properties["Revision"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Rn"))) { #optional property not found
            $Rn = $null
        } else {
            $Rn = $JsonParameters.PSobject.Properties["Rn"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ScaledMode"))) { #optional property not found
            $ScaledMode = $null
        } else {
            $ScaledMode = $JsonParameters.PSobject.Properties["ScaledMode"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Serial"))) { #optional property not found
            $Serial = $null
        } else {
            $Serial = $JsonParameters.PSobject.Properties["Serial"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ServerId"))) { #optional property not found
            $ServerId = $null
        } else {
            $ServerId = $JsonParameters.PSobject.Properties["ServerId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ServiceProfile"))) { #optional property not found
            $ServiceProfile = $null
        } else {
            $ServiceProfile = $JsonParameters.PSobject.Properties["ServiceProfile"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "SlotId"))) { #optional property not found
            $SlotId = $null
        } else {
            $SlotId = $JsonParameters.PSobject.Properties["SlotId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "SourceObjectType"))) { #optional property not found
            $SourceObjectType = $null
        } else {
            $SourceObjectType = $JsonParameters.PSobject.Properties["SourceObjectType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "TopologyScanStatus"))) { #optional property not found
            $TopologyScanStatus = $null
        } else {
            $TopologyScanStatus = $JsonParameters.PSobject.Properties["TopologyScanStatus"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "TotalMemory"))) { #optional property not found
            $TotalMemory = $null
        } else {
            $TotalMemory = $JsonParameters.PSobject.Properties["TotalMemory"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "UserLabel"))) { #optional property not found
            $UserLabel = $null
        } else {
            $UserLabel = $JsonParameters.PSobject.Properties["UserLabel"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Uuid"))) { #optional property not found
            $Uuid = $null
        } else {
            $Uuid = $JsonParameters.PSobject.Properties["Uuid"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Vendor"))) { #optional property not found
            $Vendor = $null
        } else {
            $Vendor = $JsonParameters.PSobject.Properties["Vendor"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "EquipmentChassis"))) { #optional property not found
            $EquipmentChassis = $null
        } else {
            $EquipmentChassis = $JsonParameters.PSobject.Properties["EquipmentChassis"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "InventoryDeviceInfo"))) { #optional property not found
            $InventoryDeviceInfo = $null
        } else {
            $InventoryDeviceInfo = $JsonParameters.PSobject.Properties["InventoryDeviceInfo"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "RegisteredDevice"))) { #optional property not found
            $RegisteredDevice = $null
        } else {
            $RegisteredDevice = $JsonParameters.PSobject.Properties["RegisteredDevice"].value
        }

        $PSO = [PSCustomObject]@{
            "AccountMoid" = ${AccountMoid}
            "ClassId" = ${ClassId}
            "CreateTime" = ${CreateTime}
            "DomainGroupMoid" = ${DomainGroupMoid}
            "ModTime" = ${ModTime}
            "Moid" = ${Moid}
            "ObjectType" = ${ObjectType}
            "Owners" = ${Owners}
            "SharedScope" = ${SharedScope}
            "Tags" = ${Tags}
            "VersionContext" = ${VersionContext}
            "Ancestors" = ${Ancestors}
            "Parent" = ${Parent}
            "PermissionResources" = ${PermissionResources}
            "DisplayNames" = ${DisplayNames}
            "AdminPowerState" = ${AdminPowerState}
            "AssetTag" = ${AssetTag}
            "AvailableMemory" = ${AvailableMemory}
            "BiosPostComplete" = ${BiosPostComplete}
            "ChassisId" = ${ChassisId}
            "ConnectionStatus" = ${ConnectionStatus}
            "CpuCapacity" = ${CpuCapacity}
            "DeviceMoId" = ${DeviceMoId}
            "Dn" = ${Dn}
            "FaultSummary" = ${FaultSummary}
            "Firmware" = ${Firmware}
            "Ipv4Address" = ${Ipv4Address}
            "KvmIpAddresses" = ${KvmIpAddresses}
            "ManagementMode" = ${ManagementMode}
            "MemorySpeed" = ${MemorySpeed}
            "MgmtIpAddress" = ${MgmtIpAddress}
            "Model" = ${Model}
            "Name" = ${Name}
            "NumAdaptors" = ${NumAdaptors}
            "NumCpuCores" = ${NumCpuCores}
            "NumCpuCoresEnabled" = ${NumCpuCoresEnabled}
            "NumCpus" = ${NumCpus}
            "NumEthHostInterfaces" = ${NumEthHostInterfaces}
            "NumFcHostInterfaces" = ${NumFcHostInterfaces}
            "NumThreads" = ${NumThreads}
            "OperPowerState" = ${OperPowerState}
            "OperState" = ${OperState}
            "Operability" = ${Operability}
            "PlatformType" = ${PlatformType}
            "Presence" = ${Presence}
            "Revision" = ${Revision}
            "Rn" = ${Rn}
            "ScaledMode" = ${ScaledMode}
            "Serial" = ${Serial}
            "ServerId" = ${ServerId}
            "ServiceProfile" = ${ServiceProfile}
            "SlotId" = ${SlotId}
            "SourceObjectType" = ${SourceObjectType}
            "TopologyScanStatus" = ${TopologyScanStatus}
            "TotalMemory" = ${TotalMemory}
            "UserLabel" = ${UserLabel}
            "Uuid" = ${Uuid}
            "Vendor" = ${Vendor}
            "EquipmentChassis" = ${EquipmentChassis}
            "InventoryDeviceInfo" = ${InventoryDeviceInfo}
            "RegisteredDevice" = ${RegisteredDevice}
        }

        return $PSO
    }

}

