#
# Cisco Intersight
# Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-07-16T08:45:19Z.
# Version: 1.0.9-2020
# Contact: intersight@cisco.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Definition of the list of properties defined in 'firmware.UpgradeBase', excluding properties defined in parent classes.

.PARAMETER DirectDownload
No description available.
.PARAMETER FileServer
No description available.
.PARAMETER NetworkShare
No description available.
.PARAMETER SkipEstimateImpact
User has the option to skip the estimate impact calculation.
.PARAMETER Status
Status of the upgrade operation.
.PARAMETER UpgradeType
Desired upgrade mode to choose either direct download based upgrade or network share upgrade.
.PARAMETER Distributable
No description available.
.PARAMETER Release
No description available.
.PARAMETER UpgradeImpact
No description available.
.PARAMETER UpgradeStatus
No description available.
.OUTPUTS

FirmwareUpgradeBaseAllOf<PSCustomObject>
#>

function Initialize-IntersightFirmwareUpgradeBaseAllOf {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${DirectDownload},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${FileServer},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${NetworkShare},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${SkipEstimateImpact},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("NONE", "IN_PROGRESS", "SUCCESSFUL", "FAILED", "TERMINATED")]
        [String]
        ${Status} = "NONE",
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("direct_upgrade", "network_upgrade")]
        [String]
        ${UpgradeType} = "direct_upgrade",
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Distributable},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Release},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${UpgradeImpact},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${UpgradeStatus}
    )

    Process {
        'Creating PSCustomObject: Intersight => IntersightFirmwareUpgradeBaseAllOf' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        
        $PSO = [PSCustomObject]@{
            "DirectDownload" = ${DirectDownload}
            "FileServer" = ${FileServer}
            "NetworkShare" = ${NetworkShare}
            "SkipEstimateImpact" = ${SkipEstimateImpact}
            "Status" = ${Status}
            "UpgradeType" = ${UpgradeType}
            "Distributable" = ${Distributable}
            "Release" = ${Release}
            "UpgradeImpact" = ${UpgradeImpact}
            "UpgradeStatus" = ${UpgradeStatus}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to FirmwareUpgradeBaseAllOf<PSCustomObject>

.DESCRIPTION

Convert from JSON to FirmwareUpgradeBaseAllOf<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

FirmwareUpgradeBaseAllOf<PSCustomObject>
#>
function ConvertFrom-IntersightJsonToFirmwareUpgradeBaseAllOf {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: Intersight => IntersightFirmwareUpgradeBaseAllOf' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in IntersightFirmwareUpgradeBaseAllOf
        $AllProperties = ("DirectDownload", "FileServer", "NetworkShare", "SkipEstimateImpact", "Status", "UpgradeType", "Distributable", "Release", "UpgradeImpact", "UpgradeStatus")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "DirectDownload"))) { #optional property not found
            $DirectDownload = $null
        } else {
            $DirectDownload = $JsonParameters.PSobject.Properties["DirectDownload"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "FileServer"))) { #optional property not found
            $FileServer = $null
        } else {
            $FileServer = $JsonParameters.PSobject.Properties["FileServer"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "NetworkShare"))) { #optional property not found
            $NetworkShare = $null
        } else {
            $NetworkShare = $JsonParameters.PSobject.Properties["NetworkShare"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "SkipEstimateImpact"))) { #optional property not found
            $SkipEstimateImpact = $null
        } else {
            $SkipEstimateImpact = $JsonParameters.PSobject.Properties["SkipEstimateImpact"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Status"))) { #optional property not found
            $Status = $null
        } else {
            $Status = $JsonParameters.PSobject.Properties["Status"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "UpgradeType"))) { #optional property not found
            $UpgradeType = $null
        } else {
            $UpgradeType = $JsonParameters.PSobject.Properties["UpgradeType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Distributable"))) { #optional property not found
            $Distributable = $null
        } else {
            $Distributable = $JsonParameters.PSobject.Properties["Distributable"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Release"))) { #optional property not found
            $Release = $null
        } else {
            $Release = $JsonParameters.PSobject.Properties["Release"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "UpgradeImpact"))) { #optional property not found
            $UpgradeImpact = $null
        } else {
            $UpgradeImpact = $JsonParameters.PSobject.Properties["UpgradeImpact"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "UpgradeStatus"))) { #optional property not found
            $UpgradeStatus = $null
        } else {
            $UpgradeStatus = $JsonParameters.PSobject.Properties["UpgradeStatus"].value
        }

        $PSO = [PSCustomObject]@{
            "DirectDownload" = ${DirectDownload}
            "FileServer" = ${FileServer}
            "NetworkShare" = ${NetworkShare}
            "SkipEstimateImpact" = ${SkipEstimateImpact}
            "Status" = ${Status}
            "UpgradeType" = ${UpgradeType}
            "Distributable" = ${Distributable}
            "Release" = ${Release}
            "UpgradeImpact" = ${UpgradeImpact}
            "UpgradeStatus" = ${UpgradeStatus}
        }

        return $PSO
    }

}

