#
# Cisco Intersight
# Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2021-02-05T15:05:56Z.
# Version: 1.0.9-3562
# Contact: intersight@cisco.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

This metric specification sorts TopN results by dimension value, using one of the sorting orders.

.PARAMETER Type
The dimension spec type.
.PARAMETER Ordering
Specifies the sorting order. It can be one of the following values. ""lexicographic"", ""alphanumeric"", ""numeric"", ""strlen"". * lexicographic - Sorts values by converting Strings to their UTF-8 byte array representations and comparing lexicographically, byte-by-byte. * alphanumeric - Suitable for strings with both numeric and non-numeric content, e.g. ""file12 sorts after file2"". See https://github.com/amjjd/java-alphanum for more details on how this ordering sorts values. This ordering is not suitable for numbers with decimal points or negative numbers. * numeric - Sorts values as numbers, supports integers and floating point values. Negative values are supported. This sorting order will try to parse all string values as numbers. Unparseable values are treated as nulls, and nulls precede numbers. When comparing two unparseable values (e.g., ""hello"" and ""world""), this ordering will sort by comparing the unparsed strings lexicographically. * strlen - Sorts values by the their string lengths. When there is a tie, this comparator falls back to using the String compareTo method. * version - Sorts values as versions, e.g. ""10.0 sorts after 9.0"", ""1.0.0-SNAPSHOT sorts after 1.0.0"".
.PARAMETER PreviousStop
The starting point of the sort. For example, if a previousStop value is 'b', all values before 'b' are discarded. This field can be used to paginate through all the dimension values.
.OUTPUTS

TelemetryDruidDimensionTopNMetricSpec<PSCustomObject>
#>

function Initialize-IntersightTelemetryDruidDimensionTopNMetricSpec {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("numeric", "dimension", "inverted")]
        [String]
        ${Type},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("lexicographic", "alphanumeric", "numeric", "strlen", "version")]
        [String]
        ${Ordering} = "lexicographic",
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PreviousStop}
    )

    Process {
        'Creating PSCustomObject: Intersight => IntersightTelemetryDruidDimensionTopNMetricSpec' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$Type) {
            throw "invalid value for 'Type', 'Type' cannot be null."
        }

        
        $PSO = [PSCustomObject]@{
            "type" = ${Type}
            "ordering" = ${Ordering}
            "previousStop" = ${PreviousStop}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to TelemetryDruidDimensionTopNMetricSpec<PSCustomObject>

.DESCRIPTION

Convert from JSON to TelemetryDruidDimensionTopNMetricSpec<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

TelemetryDruidDimensionTopNMetricSpec<PSCustomObject>
#>
function ConvertFrom-IntersightJsonToTelemetryDruidDimensionTopNMetricSpec {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: Intersight => IntersightTelemetryDruidDimensionTopNMetricSpec' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in IntersightTelemetryDruidDimensionTopNMetricSpec
        $AllProperties = ("type", "ordering", "previousStop")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'type' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) {
            throw "Error! JSON cannot be serialized due to the required property 'type' missing."
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ordering"))) { #optional property not found
            $Ordering = $null
        } else {
            $Ordering = $JsonParameters.PSobject.Properties["ordering"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "previousStop"))) { #optional property not found
            $PreviousStop = $null
        } else {
            $PreviousStop = $JsonParameters.PSobject.Properties["previousStop"].value
        }

        $PSO = [PSCustomObject]@{
            "type" = ${Type}
            "ordering" = ${Ordering}
            "previousStop" = ${PreviousStop}
        }

        return $PSO
    }

}

