#
# Cisco Intersight
# Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2021-02-05T15:05:56Z.
# Version: 1.0.9-3562
# Contact: intersight@cisco.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Virtual machine network interface configuration data.

.PARAMETER ClassId
The fully-qualified name of the instantiated, concrete type. This property is used as a discriminator to identify the type of the payload when marshaling and unmarshaling data.
.PARAMETER ObjectType
The fully-qualified name of the instantiated, concrete type. The value should be the same as the 'ClassId' property.
.PARAMETER AdaptorType
Virtual machine network adaptor type. * `Unknown` - The type of the network adaptor type is unknown. * `E1000` - Emulated version of the Intel 82545EM Gigabit Ethernet NIC. * `SRIOV` - Representation of a virtual function (VF) on a physical NIC with SR-IOV support. * `VMXNET2` - VMXNET 2 (Enhanced) is available only for some guest operating systems on ESX/ESXi 3.5 and later. * `VMXNET3` - VMXNET 3 offers all the features available in VMXNET 2 and adds several new features.
.PARAMETER Bridge
Virtual machine network bridge name.
.PARAMETER ConnectAtPowerOn
Connect the adaptor at virtual machine power on.
.PARAMETER DirectPathIo
Enable the direct path I/O.
.PARAMETER MacAddress
Virtual machine network mac address.
.OUTPUTS

VirtualizationNetworkInterface<PSCustomObject>
#>

function Initialize-IntersightVirtualizationNetworkInterface {
    [CmdletBinding()]
    Param (
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("virtualization.NetworkInterface")]
        [String]
        ${ClassId} = "virtualization.NetworkInterface",
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("virtualization.NetworkInterface")]
        [String]
        ${ObjectType} = "virtualization.NetworkInterface",
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("Unknown", "E1000", "SRIOV", "VMXNET2", "VMXNET3")]
        [String]
        ${AdaptorType} = "Unknown",
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Bridge},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ConnectAtPowerOn},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${DirectPathIo},
        [Parameter(ValueFromPipelineByPropertyName = $true)]
        [ValidatePattern("^$|^00:25:B5:([0-9a-fA-F]{2}:){2}([0-9a-fA-F]{2})$")]
        [String]
        ${MacAddress}
    )

    Process {
        'Creating PSCustomObject: Intersight => IntersightVirtualizationNetworkInterface' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if (!$ClassId) {
            throw "invalid value for 'ClassId', 'ClassId' cannot be null."
        }

        if (!$ObjectType) {
            throw "invalid value for 'ObjectType', 'ObjectType' cannot be null."
        }

        
        $PSO = [PSCustomObject]@{
            "ClassId" = ${ClassId}
            "ObjectType" = ${ObjectType}
            "AdaptorType" = ${AdaptorType}
            "Bridge" = ${Bridge}
            "ConnectAtPowerOn" = ${ConnectAtPowerOn}
            "DirectPathIo" = ${DirectPathIo}
            "MacAddress" = ${MacAddress}
        }

        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to VirtualizationNetworkInterface<PSCustomObject>

.DESCRIPTION

Convert from JSON to VirtualizationNetworkInterface<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

VirtualizationNetworkInterface<PSCustomObject>
#>
function ConvertFrom-IntersightJsonToVirtualizationNetworkInterface {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: Intersight => IntersightVirtualizationNetworkInterface' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in IntersightVirtualizationNetworkInterface
        $AllProperties = ("ClassId", "ObjectType", "AdaptorType", "Bridge", "ConnectAtPowerOn", "DirectPathIo", "MacAddress")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'ClassId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ClassId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'ClassId' missing."
        } else {
            $ClassId = $JsonParameters.PSobject.Properties["ClassId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ObjectType"))) {
            throw "Error! JSON cannot be serialized due to the required property 'ObjectType' missing."
        } else {
            $ObjectType = $JsonParameters.PSobject.Properties["ObjectType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "AdaptorType"))) { #optional property not found
            $AdaptorType = $null
        } else {
            $AdaptorType = $JsonParameters.PSobject.Properties["AdaptorType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "Bridge"))) { #optional property not found
            $Bridge = $null
        } else {
            $Bridge = $JsonParameters.PSobject.Properties["Bridge"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ConnectAtPowerOn"))) { #optional property not found
            $ConnectAtPowerOn = $null
        } else {
            $ConnectAtPowerOn = $JsonParameters.PSobject.Properties["ConnectAtPowerOn"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "DirectPathIo"))) { #optional property not found
            $DirectPathIo = $null
        } else {
            $DirectPathIo = $JsonParameters.PSobject.Properties["DirectPathIo"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "MacAddress"))) { #optional property not found
            $MacAddress = $null
        } else {
            $MacAddress = $JsonParameters.PSobject.Properties["MacAddress"].value
        }

        $PSO = [PSCustomObject]@{
            "ClassId" = ${ClassId}
            "ObjectType" = ${ObjectType}
            "AdaptorType" = ${AdaptorType}
            "Bridge" = ${Bridge}
            "ConnectAtPowerOn" = ${ConnectAtPowerOn}
            "DirectPathIo" = ${DirectPathIo}
            "MacAddress" = ${MacAddress}
        }

        return $PSO
    }

}

