
#Get the FirmwareBoardControllerDescriptor to delete
$FirmwareBoardControllerDescriptor = Remove-IntersightFirmwareBoardControllerDescriptor -Name FirmwareBoardControllerDescriptorName
$FirmwareBoardControllerDescriptor | Remove-IntersightFirmwareBoardControllerDescriptor

#Remove the server profile by Moid.
Remove-IntersightFirmwareBoardControllerDescriptor -Moid 123bc2222287wee
