
#Get the FirmwareSasExpanderDescriptor to Update
$FirmwareSasExpanderDescriptor = Get-IntersightFirmwareSasExpanderDescriptor -Name FirmwareSasExpanderDescriptorName
$FirmwareSasExpanderDescriptor | Set-IntersightFirmwareSasExpanderDescriptor -Description 'Updated description'
