
#Get the KubernetesTrustedRegistriesPolicy to delete
$KubernetesTrustedRegistriesPolicy = Remove-IntersightKubernetesTrustedRegistriesPolicy -Name KubernetesTrustedRegistriesPolicyName
$KubernetesTrustedRegistriesPolicy | Remove-IntersightKubernetesTrustedRegistriesPolicy

#Remove the server profile by Moid.
Remove-IntersightKubernetesTrustedRegistriesPolicy -Moid 123bc2222287wee
