
#Get the KubernetesTrustedRegistriesPolicy to Update
$KubernetesTrustedRegistriesPolicy = Get-IntersightKubernetesTrustedRegistriesPolicy -Name KubernetesTrustedRegistriesPolicyName
$KubernetesTrustedRegistriesPolicy | Set-IntersightKubernetesTrustedRegistriesPolicy -Description 'Updated description'