
#Get the KubernetesAciCniTenantClusterAllocation to Update
$KubernetesAciCniTenantClusterAllocation = Get-IntersightKubernetesAciCniTenantClusterAllocation -Name KubernetesAciCniTenantClusterAllocationName
$KubernetesAciCniTenantClusterAllocation | Set-IntersightKubernetesAciCniTenantClusterAllocation -Description 'Updated description'